version: '3.9'

services:

  api:
    build: .
    restart: on-failure
    ports:
      - "5001:443"
      - "5000:80"
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/cert.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Test1234!
      - ASPNETCORE_Environment=Production
      - ConnectionStrings__DbConnection=Server=db;Port=5432;Database=mydb;User ID=feapi;Password=changeme;
    depends_on:
      db:
        condition: service_started

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=feapi
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=mydb
    ports:
      - '5432:5432'
